name: "Email Validation Test"
on:
  pull_request:

jobs:
  check-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.4.1-stable
      - name: Run email check
        working-directory: tests/godot
        run: |
          godot --headless --path . -q -s ../check_email.gd
